# Basis Image wählen
FROM ubuntu:22.04

# Zeitzone setzen
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get update && apt-get -y install tzdata

# Systemupdates und notwendige Pakete installieren
RUN apt-get update && apt-get install -y \
    apt-utils \
    apache2 \
    php \
    libapache2-mod-php \
    php-mysql \
    && rm -rf /var/lib/apt/lists/*

# Apache Module aktivieren, die häufig für Webanwendungen benötigt werden
RUN a2enmod rewrite
RUN a2enmod ssl
RUN a2enmod headers

# Das Startskript in den Container kopieren
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Apache-Konfiguration kopieren
COPY bookApp.conf /etc/apache2/sites-available/bookApp.conf
RUN a2ensite bookApp
RUN a2dissite 000-default.conf

# Anwendungscode kopieren
COPY ./bookApp/ /var/www/bookApp/

# Berechtigungen setzen - wichtig für Apache
RUN chown -R www-data:www-data /var/www/bookApp

# Port freigeben
EXPOSE ${WEB_PORT}


# Start-Skript als ENTRYPOINT festlegen
ENTRYPOINT ["/bin/bash", "/start.sh"]

# Apache im Vordergrund starten
CMD ["apache2ctl", "-D", "FOREGROUND"]
